Add Monitoring Configuration
Hydrospheredata/hydro-serving-sdk pull request #72
Opened 2020-08-14 11:44 UTC by trthhrtz

2020-08-19 08:09 UTC, KineticCookie requested changes
Define monitoring configuration as a class

2020-08-19 08:09 UTC, KineticCookie commented on hydrosdk/modelversion.py
> +                 training_data: Optional[str] = None, monitoring_configuration: dict = None):
```suggestion
                 training_data: Optional[str] = None, monitoring_configuration: Optional[MonitoringConfiguration] = None):
```

2020-08-19 11:39 UTC, trthhrtz commented on hydrosdk/modelversion.py
> +                 training_data: Optional[str] = None, monitoring_configuration: dict = None):
Fixed

2020-08-19 11:40 UTC, trthhrtz commented
MonitoringConfiguration class is defined

2020-08-24 10:52 UTC, KineticCookie approved these changes

2020-09-14 13:19 UTC, merged